### ISSUE TITLE
Gold linker?

### ISSUE THREAD

**Issue by derenrich** [AnacondaRecipes/tensorflow_recipes#5]
When using this recipe I'm running into issues where it's trying to use the gold linker but tensorflow cannot be compiled using the gold linker. Have you guys run into this?  In particular the error I get is: 

```
/root/miniconda2/conda-bld/tensorflow-base_1537569436989/_build_env/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.2.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld.gold: fatal error: unable to parse version script file bazel-out/host/bin/tensorflow/python/pywrap_tensorflow_internal_versionscript.lds
```

**Comment by mingwandroid** [comment]
In general, well written conda recipes do not require docker at all.

**Comment by jjhelmus** [comment]
What recipe are you trying to build?  From the log it looks like `tensorflow-base` which is no longer used, try `tensorflow-base-cpu`.

**Comment by jjhelmus** [comment]
The [conda/c3i-linux-64](https://hub.docker.com/r/conda/c3i-linux-64/) container is used for CPU builds. GPU builds use containers from https://github.com/jjhelmus/docker-images.

**Comment by derenrich** [comment]
the command that is failing for me is 
> conda build  tensorflow-base-cpu --variant-config-file tensorflow-base-cpu/conda_build_config.yaml

I'm running it in a centos-6 docker (also tried centos-7). I'm trying again in your docker container now. Really unsure why I can't reproduce this.

**Comment by derenrich** [comment]
no that didn't help. is the runner code for this open source?

**Comment by mingwandroid** [comment]
Are you using our build matrix?

https://github.com/AnacondaRecipes/aggregate/blob/master/conda_build_config.yaml

pass that to conda-build with -m perhaps?

**Comment by mingwandroid** [comment]
There is no "runner code" as such, just conda-build running on docker images.

**Comment by derenrich** [comment]
Hmm well the following Dockerfile fails to build the package 

```
FROM conda/c3i-linux-64

RUN git clone "https://github.com/AnacondaRecipes/tensorflow_recipes.git"

WORKDIR tensorflow_recipes
RUN git reset --hard c70ac5d30db784a293f0155b912eb6925b064611

ADD matrix.yml .

RUN  conda build tensorflow-base-cpu -m matrix.yml  --variant-config-file tensorflow-base-cpu/conda_build_config.yaml
```
Where `matrix.yml` holds the build matrix you referenced

It emits the error: 

```
/opt/conda/conda-bld/tensorflow-base_1537662217475/_build_env/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.2.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld.gold: fatal error: unable to parse version script file bazel-out/k8-opt/bin/tensorflow/contrib/lite/python/interpreter_wrapper/tensorflow_wrap_interpreter_wrapper_versionscript.lds
```

You don't do anything special/different?

**Comment by jjhelmus** [comment]
The linux `tensorflow-base` packages were built against the recipe present in commit 4f33574d0e264f638f7ea7816c01f557288b7fdb.  After this, in 8b70206ab9f5f1bbe972cc58f293d347016b7f53 a patch was added to the recipe that was needed for macOS which unfortunately is causing the linking errors seen here.  This patch should not be applied on linux.  I'm updating the recipe to add a selector to fix this.
