### ISSUE TITLE
no tensorflow-gpu builds for mac

### ISSUE THREAD

**Issue by pgunn** [AnacondaRecipes/tensorflow_recipes#7]
Hi,
I am a maintainer of a cross-platform piece of scientific software written in Python which uses tensorflow. Right now our standard environment file (used across all 3 platforms) uses the normal "tensorflow" package, but given that tensorflow-gpu can use a GPU if present and the CPU if not, it'd be pretty nice for us to be able to switch to the tensorflow-gpu package, which is available in the conda repos for Linux and Windows but not OSX.

It'd be pretty great if there were tensorflow-gpu builds for OSX as well so we could have consistent environment files and use GPUs when present and CPUs when not. Either that or some metapackage we could refer to that has a dep on tensorflow-gpu on Linux and Windows and a dep on tensorflow on OSX.

**Comment by jjhelmus** [comment]
The upstream provider of Tensorflow, Google, does not support GPU builds on macOS.  If the upstream adds support for the platform we will certainly build packages.

**Comment by pgunn** [comment]
Does the metapackage idea seem workable, or is that too technically ugly to be worth considering?

**Comment by jjhelmus** [comment]
Having a package which claim to be a GPU accelerated version of Tensorflow but in fact is not seems like a bad experience.

**Comment by jjhelmus** [comment]
Having a metapackage on a personal channel would be an option.

**Comment by pgunn** [comment]
We may go down that route. I was imagining something (ignore the name) like

tensorflow-gpu
tensorflow-nogpu

and then a metapackage called tensorflow (or tensorflow-best) that would pick -gpu if it's platform-available and -nogpu otherwise

**Comment by jjhelmus** [comment]
There is already a `tensorflow` packages that can be used to install any of the variants but the default version is the non-gpu "mkl" variant.  The issue with making the gpu variant the default is that on system with a GPU this version does not work at all.

**Comment by jjhelmus** [comment]
In addition, `pip install tensorflow` installs a non-GPU version of tensorflow.  Having different behavior in conda would be surprising to many users.

**Comment by katietz** [comment]
There are ways to build tensorflow on OSX using gpu, but this seems to be nothing recommented for now.  After providing most recent version for OSX, I will give GPU variant a try.

**Comment by pgunn** [comment]
Closing this issue - nothing to do if upstream doesn't provide
